const packageJson = JSON.parse(require('fs').readFileSync('./package.json', 'utf8'));

module.exports = {
  name: packageJson.title,
  version: packageJson.version,
  description: packageJson.description,
  options_ui_html: 'options/ui/ui.html',
  options_page: 'options/options.html',
  background: {
    scripts: ['js/background.js'],
    persistent: true,
  },
  content_scripts: [{
    matches: ['*://tweetdeck.twitter.com/*'],
    js: ['js/content.js'],
    css: ['css/index.css'],
  }],
  permissions: [
    'storage',
    'https://api.embed.ly/1/*',
    'https://backend.deviantart.com/*',
    'https://500px.com/oembed*',
    'https://api.dailymotion.com/video/*',
    'https://api.dribbble.com/v1/shots/*',
    'https://*.imgur.com/*',
    'https://*.instagram.com/*',
    'https://images4-focus-opensocial.googleusercontent.com/gadgets/proxy*',
    'http://erambert.me/*',
    'https://embed.spotify.com/oembed/*',
    'https://api.streamable.com/*',
    'https://api.twitch.tv/kraken/*',
    'https://*.bandcamp.com/*',
    'https://cl.ly/*',
    'https://giphy.com/services/oembed*',
    '*://tweetdeck.twitter.com/*',
    'contextMenus',
  ],
  icons: {
    16: 'icons/icon 16.png',
    48: 'icons/icon 48.png',
    128: 'icons/icon 128.png',
  },
  default_locale: 'en',
  web_accessible_resources: ['js/inject.js', 'js/content.js.map', 'js/inject.js.map', 'js/background.js.map', 'emojis/sheet_twitter_64.png', 'emojis/emoji-happy.svg', 'icons/controller-play.svg', 'options/options.html'],
  content_security_policy: 'img-src \'self\' *; default-src; connect-src * https:; style-src \'unsafe-inline\'',
};
